services:
  product-service:
    build:
      context: ./ProductService
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIROMENT = Development
      - ConnectionStrings__DefaultConnection =Server=host.docker.internal;Database=ProductDb;User=sa;Password=5Mr0ZvgT;Encrypt=False;